// Generated by @vibelogin/mcp
import { createHostedServerHelpers } from "@vibelogin/nextjs/server";

const { getSession, currentUser } = createHostedServerHelpers({
  projectId: process.env.VIBELOGIN_PROJECT_ID!,
});

export { getSession, currentUser };
