// Generated by @vibelogin/mcp
import { createHostedHandler } from "@vibelogin/nextjs/handler";

export const { GET, POST, PATCH, DELETE } = createHostedHandler({
  secretKey: process.env.VIBELOGIN_SECRET_KEY!,
  publishableKey: process.env.VIBELOGIN_PUBLISHABLE_KEY!,
});
