// Generated by @vibelogin/mcp
import { createCallbackHandler } from "@vibelogin/nextjs/callback";

export const { GET } = createCallbackHandler({
  secretKey: process.env.VIBELOGIN_SECRET_KEY!,
  defaultRedirect: "/dashboard",
});
