// Generated by @vibelogin/mcp
"use client";
import { VibeLogin } from "@vibelogin/nextjs/components";

export default function LoginPage() {
  return (
    <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", backgroundColor: "#111827" }}>
      <div style={{ width: "100%", maxWidth: 420, padding: "0 16px" }}>
        <h1 style={{ fontSize: 24, fontWeight: 600, textAlign: "center", marginBottom: 24, color: "#f9fafb" }}>
          Sign in
        </h1>
        <VibeLogin
          slug={"cashflow"}
          callbackPath="/auth/callback"
          redirectAfterLogin={"/dashboard"}
        />
      </div>
    </main>
  );
}
