// Generated by @vibelogin/mcp
"use client";
import { VibeAuthProvider } from "@vibelogin/nextjs/client";

export function Providers({ children }: { children: React.ReactNode }) {
  return <VibeAuthProvider>{children}</VibeAuthProvider>;
}
