// Generated by @vibelogin/mcp
"use client";
import { useSearchParams } from "next/navigation";
import { Suspense } from "react";
import { ResetPasswordForm } from "@vibelogin/nextjs/components";

function ResetForm() {
  const params = useSearchParams();
  const token = params.get("token") || "";

  return <ResetPasswordForm token={token} redirectAfterReset="/login" />;
}

export default function ResetPasswordPage() {
  return (
    <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", backgroundColor: "#111827" }}>
      <div style={{ width: "100%", maxWidth: 400, padding: "0 16px" }}>
        <h1 style={{ fontSize: 24, fontWeight: 600, textAlign: "center", marginBottom: 24, color: "#f9fafb" }}>
          Reset password
        </h1>
        <Suspense>
          <ResetForm />
        </Suspense>
      </div>
    </main>
  );
}
