// Generated by @vibelogin/mcp
"use client";
import { useAuth } from "@vibelogin/nextjs/client";
import { useRouter } from "next/navigation";

export function SignOutButton() {
  const { signOut } = useAuth();
  const router = useRouter();

  return (
    <button
      onClick={async () => {
        await signOut();
        router.push("/login");
      }}
      className="rounded-lg border border-border px-3 py-1.5 text-xs font-medium transition hover:bg-surface-hover"
    >
      Sign out
    </button>
  );
}
