// Generated by @vibelogin/mcp
"use client";
import { useSearchParams } from "next/navigation";
import { Suspense } from "react";
import { MagicLinkVerifyHandler } from "@vibelogin/nextjs/components";

function VerifyHandler() {
  const params = useSearchParams();
  const token = params.get("token") || "";

  return <MagicLinkVerifyHandler token={token} redirectAfterLogin="/" />;
}

export default function MagicLinkVerifyPage() {
  return (
    <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", backgroundColor: "#111827" }}>
      <Suspense>
        <VerifyHandler />
      </Suspense>
    </main>
  );
}
